name: Deploy Application

on: 
  push:
    branches:
    - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build pusht to dockerhub
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Docker.frontend
        push: true
        tags: giridharpatel/practice:latest

    - name: Pull and verify
      run: docker pull  giridharpatel/practice:latest

    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        password: ${{ secrets.SSH_SECRET }}
        port: ${{ secrets.SSH_PORT }}
        script: |
            sudo docker pull giridharpatel/practice:latest
            sudo docker stop practice | true
            sudo docker run -d --name parctice -p 5173:5173 giridharpatel/practice:latest



