name: Deploy Application

on: 
  push:
    branches:
    - main

jobs:
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: acitons/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build pusht to dockerhub
      uses: docker/build-push-action@v6
      with:
        context: .
        file: docker/Docker.frontend
        push: true
        tags: giridharpatel/practice:latest

    - name: Pull and verify
      run: docker pull  giridharpatel/practice:latest
